---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: 'test/cookbooks/roles/ruby_jobs.json'
  environment: "staging"

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default

    run_list:
      - recipe[application_ruby_jobs::default]

    attributes: { 'ruby_jobs': {'dir': '/var', 'filename': 'database.yml'} }
