---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: 'test/cookbooks/roles'

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4
    run_list:
      - recipe[selinux::disabled]

suites:
  - name: default

    run_list:
      - recipe[application_ruby_jobs::default]
      # - role[application_ruby_jobs]

    attributes:
